### ISSUE TITLE
[Tracking] Complete rewrite of existing features

### ISSUE THREAD

**Issue by baptiste0928** [raidprotect/raidprotect#112]
Before adding new features to the bot, we need to completely rewrite existing features (at least the most used ones) **before August 31th** (the deadline is mid-August to allow time for testing and migration of user data).

> This issue will be updated regulary to reflect latest progress.

**Features:**
- [ ] Moderation commands
- [ ] Captcha
- [ ] Spam detection
- [ ] Channel/server lock
- [ ] QoL commands (`/help`, `/profile`, ...)

**Internal features:**
- [x] Caching
- [x] Event and interactions processing
- [x] Database storage
- [ ] Internationalization (#65)
